### PR TITLE
Fix segfault on ^C.  Resolves #87.

### LINKED ISSUE #87: segfault on ctrl-c
Reproduction: ctrl-c during our build

@asottile 

```
Bottom (innermost) frame selected; you cannot go down.                                                                                  │
(gdb) bt                                                                                                                                │
#0  0x000000000045ec23 in PyList_Insert ()                                                                                              │
#1  0x00002b92179fc573 in _exception_to_sass_error (sass_args=<value optimized out>, cookie=<value optimized out>) at pysass.cpp:298    │
#2  _call_py_f (sass_args=<value optimized out>, cookie=<value optimized out>) at pysass.cpp:385                                        │
#3  0x00002b921798753b in Sass::Eval::operator() (this=<value optimized out>, c=0x2ef4bd0) at libsass/eval.cpp:528                      │
#4  0x00002b921796b77a in Sass::Expand::operator() (this=0x7ffce6555be0, d=<value optimized out>) at libsass/expand.cpp:136             │
#5  0x00002b921796ccd1 in Sass::Expand::append_block (this=0x7ffce6555be0, b=0x2ef4280) at libsass/expand.cpp:426                       │
#6  Sass::Expand::operator() (this=0x7ffce6555be0, b=0x2ef4280) at libsass/expand.cpp:37                                                │
#7  0x00002b921797162f in Sass::Expand::operator() (this=0x7ffce6555be0, r=0x2ef5020) at libsass/expand.cpp:54                          │
#8  0x00002b92179700d9 in Sass::Expand::append_block (this=0x7ffce6555be0, i=<value optimized out>) at libsass/expand.cpp:426           │
#9  Sass::Expand::operator() (this=0x7ffce6555be0, i=<value optimized out>) at libsass/expand.cpp:171                                   │
#10 0x00002b921796ccd1 in Sass::Expand::append_block (this=0x7ffce6555be0, b=0x2db39b0) at libsass/expand.cpp:426                       │
#11 Sass::Expand::operator() (this=0x7ffce6555be0, b=0x2db39b0) at libsass/expand.cpp:37                                                │
#12 0x00002b921796751d in Sass::Context::parse_file (this=<value optimized out>) at libsass/context.cpp:286                             │
#13 0x00002b921793bb4a in sass_parse_block (c_ctx=0x28db260, cpp_ctx=0x2d91120) at libsass/sass_context.cpp:382                         │
#14 0x00002b921793cb43 in sass_compile_context (c_ctx=0x28db260, cpp_opt=<value optimized out>) at libsass/sass_context.cpp:411         │
#15 0x00002b921793cee3 in sass_compile_file_context (file_ctx=0x28db260) at libsass/sass_context.cpp:524                                │
#16 0x00002b92179fb59b in PySass_compile_filename (self=<value optimized out>, args=<value optimized out>) at pysass.cpp:499            │
#17 0x00000000004df571 in PyEval_EvalFrameEx ()                                                                                         │
#18 0x00000000004e0e21 in PyEval_EvalCodeEx ()                                                                                          │
#19 0x00000000004dee85 in PyEval_EvalFrameEx ()                                                                                         │
#20 0x00000000004e0e21 in PyEval_EvalCodeEx ()                                                                                          │
#21 0x00000000004dee85 in PyEval_EvalFrameEx ()                                                                                         │
#22 0x00000000004e0e21 in PyEval_EvalCodeEx ()                                                                                          │
#23 0x00000000004dee85 in PyEval_EvalFrameEx ()                                                                                         │
#24 0x00000000004e0e21 in PyEval_EvalCodeEx ()                                                                                          │
#25 0x00000000004dee85 in PyEval_EvalFrameEx ()                                                                                         │
#26 0x00000000004e0e21 in PyEval_EvalCodeEx ()                                                                                          │
#27 0x00000000004dee85 in PyEval_EvalFrameEx ()                                                                                         │
#28 0x00000000004e0e21 in PyEval_EvalCodeEx ()                                                                                          │
#29 0x00000000004e0f32 in PyEval_EvalCode ()                                                                                            │
#30 0x0000000000501cce in PyRun_FileExFlags ()                                                                                          │
#31 0x0000000000501ef7 in PyRun_SimpleFileExFlags ()                                                                                    │
#32 0x000000000051783d in Py_Main ()                                                                                                    │
#33 0x00002b9217070c8d in __libc_start_main (main=<value optimized out>, argc=<value optimized out>, ubp_av=<value optimized out>,      │
    init=<value optimized out>, fini=<value optimized out>, rtld_fini=<value optimized out>, stack_end=0x7ffce6556fe8)                  │
    at libc-start.c:226                                                                                                                 │
#34 0x000000000041b329 in _start ()
```

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by dahlia** [comment]
Shouldn’t it has changelog?

**Comment by asottile** [comment]
We can include this in the changelog when cutting a release

**Comment by dahlia** [comment]
@asottile Let me know your PyPI username.  I want to add you as a maintainer of the PyPI release.

**Comment by asottile** [comment]
I'm asottile on pypi as well

**Comment by dahlia** [comment]
@asottile Done!

**Comment by asottile** [comment]
@dahlia can we put together a checklist for making a release?  I want to make sure I don't forget anything when I do one :)

**Comment by dahlia** [comment]
@asottile That seems a good idea.  I will add CONTRIBUTING.rst including the checklist.

**Comment by dahlia** [comment]
@asottile I just wrote [maintainer’s guide][1].  How is it?

[1]: https://github.com/dahlia/libsass-python/blob/python/CONTRIBUTING.rst#maintainers-guide

**Comment by asottile** [comment]
Looks great!

**Comment by dahlia** [comment]
@asottile Oh, I just added more.  Please reload the page.  :wink:

**Comment by dahlia** [comment]
Added once more — about the docs website.

**Pull request merged**
