### PR TITLE
update documentation

### PR DESCRIPTION
**Pull request by sherwyngoh**

### CODE REVIEW

**Comment by dahlia** [comment]
`pip` must automatically download corresponding binary wheel from PyPI.  Doesn’t it work?

**Comment by asottile** [comment]
It's possible they're using old pip (<1.5) which won't install wheels by default?

**Comment by dahlia** [comment]
So the guide should recommend to install the latest version of pip, rather
than to manually download the corresponding wheel from PyPI.

**Comment by asottile** [comment]
We've since switched our main branch from python -> master, please recreate this pull request :)

**Pull request closed without merging**
