### PR TITLE
Fixing pep8, typo, misc

### PR DESCRIPTION
**Pull request by frediz**
In the process of packaging libsass-python for debian, the following has been
reported, and the patch fixes all but "'sys' imported but unused" because this
one seemed to be expected.
```
$ pyflakes .
./sasstests.py:942: 'sys' imported but unused
./docs/conf.py:15: 'warnings' imported but unused

$ pyflakes3 .
./sasstests.py:942: 'sys' imported but unused
./docs/conf.py:15: 'warnings' imported but unused

$ codespell --quiet-level=3
./sass.py:531: conjuction  ==> conjunction
./sassutils/wsgi.py:21: Everytime  ==> Every time

$ pep8 --ignore W191 .
./ez_setup.py:42:1: E302 expected 2 blank lines, found 1
./ez_setup.py:133:9: E128 continuation line under-indented for visual indent
./ez_setup.py:149:80: E501 line too long (82 > 79 characters)
./ez_setup.py:163:1: E302 expected 2 blank lines, found 1
./ez_setup.py:175:1: E302 expected 2 blank lines, found 1
./ez_setup.py:194:1: E302 expected 2 blank lines, found 1
./ez_setup.py:207:1: E302 expected 2 blank lines, found 1
./ez_setup.py:211:1: E302 expected 2 blank lines, found 1
./ez_setup.py:222:1: E302 expected 2 blank lines, found 1
./ez_setup.py:226:1: E302 expected 2 blank lines, found 1
./ez_setup.py:237:1: E302 expected 2 blank lines, found 1
./ez_setup.py:255:1: E302 expected 2 blank lines, found 1
./ez_setup.py:265:1: E302 expected 2 blank lines, found 1
./ez_setup.py:266:9: E128 continuation line under-indented for visual indent
./ez_setup.py:290:1: E302 expected 2 blank lines, found 1
./ez_setup.py:296:1: E302 expected 2 blank lines, found 1
./ez_setup.py:321:1: E302 expected 2 blank lines, found 1
./sasstests.py:205:37: E241 multiple spaces after ','
./sasstests.py:212:37: E241 multiple spaces after ','
./sasstests.py:214:38: E241 multiple spaces after ','
./sasstests.py:221:37: E241 multiple spaces after ','
./sasstests.py:223:37: E241 multiple spaces after ','
./docs/conf.py:6:80: E501 line too long (80 > 79 characters)
./docs/conf.py:24:80: E501 line too long (80 > 79 characters)
./docs/conf.py:29:80: E501 line too long (80 > 79 characters)
./docs/conf.py:41:1: E265 block comment should start with '# '
./docs/conf.py:61:1: E265 block comment should start with '# '
./docs/conf.py:65:1: E265 block comment should start with '# '
./docs/conf.py:67:1: E265 block comment should start with '# '
./docs/conf.py:73:80: E501 line too long (80 > 79 characters)
./docs/conf.py:74:1: E265 block comment should start with '# '
./docs/conf.py:77:1: E265 block comment should start with '# '
./docs/conf.py:81:1: E265 block comment should start with '# '
./docs/conf.py:85:1: E265 block comment should start with '# '
./docs/conf.py:91:1: E265 block comment should start with '# '
./docs/conf.py:94:80: E501 line too long (80 > 79 characters)
./docs/conf.py:103:1: E265 block comment should start with '# '
./docs/conf.py:106:1: E265 block comment should start with '# '
./docs/conf.py:110:1: E265 block comment should start with '# '
./docs/conf.py:113:1: E265 block comment should start with '# '
./docs/conf.py:117:1: E265 block comment should start with '# '
./docs/conf.py:122:1: E265 block comment should start with '# '
./docs/conf.py:131:1: E265 block comment should start with '# '
./docs/conf.py:135:1: E265 block comment should start with '# '
./docs/conf.py:138:1: E265 block comment should start with '# '
./docs/conf.py:142:1: E265 block comment should start with '# '
./docs/conf.py:145:1: E265 block comment should start with '# '
./docs/conf.py:148:1: E265 block comment should start with '# '
./docs/conf.py:151:1: E265 block comment should start with '# '
./docs/conf.py:154:1: E265 block comment should start with '# '
./docs/conf.py:157:1: E265 block comment should start with '# '
./docs/conf.py:160:1: E265 block comment should start with '# '
./docs/conf.py:165:1: E265 block comment should start with '# '
./docs/conf.py:168:1: E265 block comment should start with '# '
./docs/conf.py:174:80: E501 line too long (80 > 79 characters)
./docs/conf.py:177:1: E122 continuation line missing indentation or outdented
./docs/conf.py:178:1: E122 continuation line missing indentation or outdented
./docs/conf.py:178:1: E265 block comment should start with '# '
./docs/conf.py:180:1: E122 continuation line missing indentation or outdented
./docs/conf.py:181:1: E122 continuation line missing indentation or outdented
./docs/conf.py:181:1: E265 block comment should start with '# '
./docs/conf.py:183:1: E122 continuation line missing indentation or outdented
./docs/conf.py:184:1: E122 continuation line missing indentation or outdented
./docs/conf.py:184:1: E265 block comment should start with '# '
./docs/conf.py:188:80: E501 line too long (80 > 79 characters)
./docs/conf.py:190:3: E121 continuation line under-indented for hanging indent
./docs/conf.py:196:1: E265 block comment should start with '# '
./docs/conf.py:200:1: E265 block comment should start with '# '
./docs/conf.py:203:1: E265 block comment should start with '# '
./docs/conf.py:206:1: E265 block comment should start with '# '
./docs/conf.py:209:1: E265 block comment should start with '# '
./docs/conf.py:212:1: E265 block comment should start with '# '
./docs/conf.py:215:80: E501 line too long (80 > 79 characters)
./docs/conf.py:225:1: E265 block comment should start with '# '
./docs/conf.py:228:80: E501 line too long (80 > 79 characters)
./docs/conf.py:234:3: E121 continuation line under-indented for hanging indent
./docs/conf.py:240:1: E265 block comment should start with '# '
./docs/conf.py:243:1: E265 block comment should start with '# '
./docs/conf.py:246:1: E265 block comment should start with '# '
```

### CODE REVIEW

**Comment by asottile** [comment]
A few of these files shouldn't live in the debian package.

Since we'd like this to not regress since you've put effort into it could you update setup.cfg to not exclude these?

The current contents:
```ini
[flake8]
exclude = build,dist,docs,ez_setup.py,upload_appveyor_builds.py
```

**Comment by frediz** [comment]
Well, except sasstests.py (and maybe it shouldn't either), none of those file are packaged actually :)
But that's just the kind of thing Debian maintainers/developers check on the whole source tree and if that can help the uptream project, it's a good thing to share.

**Comment by dahlia** [comment]
[ez_setup.py][1] is actually not a part of the project.  It’s just copied from setuptools.

[1]: https://bitbucket.org/pypa/setuptools/src/a3e72c93835f0fe392732dd3a26f2071d8fcfe82/ez_setup.py?at=default&fileviewer=file-view-default

**Comment by frediz** [comment]
Right dahlia, my fault, I launched pep8 over a dirty source tree.

**Comment by asottile** [comment]
Needs rebase

**Comment by asottile** [comment]
We've since switched our main branch from python -> master, please recreate this pull request :)

**Pull request closed without merging**
