### PR TITLE
Restore bytes test for warnings removed in c54f786

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by dahlia** [comment]
Sorry, I misunderstood it as just a duplicate of the above one.

**Comment by asottile** [comment]
Yep no problem -- my fault for not naming it differently initially :D

**Comment by asottile** [comment]
@dahlia  seems py26 is still sad from the flake8 changes (py27 specific syntax in the appveyor upload script), other than that this is passing

**Comment by dahlia** [comment]
Oh that’s because I wrote the script only for me at first, and assume it runs on only Python 3.4+.  I will make flake8 to ignore this script soon (or feel free if you’d like to fix it).

**Pull request merged**
