### PR TITLE
Support for string compilation using indented (SASS) string syntax.

### LINKED ISSUE #41: Support indented syntax for string input
libsass supports the [indented syntax](http://sass-lang.com/documentation/file.INDENTED_SYNTAX.html), e.g.,
```sass
p
  a
    color: blue
```
This binding correctly handles files written in the indented syntax if passed as filenames with the `.sass` extension, e.g.,
```python
sass.compile(filename="foobar.sass")
```
... but has no support for the indented syntax as string input, e.g.,
```python
sass.compile(string="p\n  a\n    color: blue\n")
```
Perhaps a keyword parameter, e.g., `syntax="sass"` / `syntax="scss"`?

### PR DESCRIPTION
**Pull request by amcgregor**
Fixes #41.

### CODE REVIEW

**Comment by asottile** [comment]
Looks like your change fails flake8.  Could you fix that and add a quick test?

Other than that, :shipit:

**Comment by amcgregor** [comment]
Yup, noticed the flake8 failure… wow those Travis tests take a long time to complete.  Updating now.

**Comment by amcgregor** [comment]
Should be good to go.

**Comment by asottile** [comment]
Thanks for the PR!

**Comment by amcgregor** [comment]
It never hurts to help.  I may tackle the `@import` callback thing (#81) later, as it's needed at work.  Do you have a release schedule for pypi published releases?

**Comment by asottile** [comment]
I usually release whenever someone asks or when I need a new release.  Would you like me to cut a new version?

**Comment by amcgregor** [comment]
@asottile Ah, might wait until I've pushed the `@import` callback code, but after that for sure.  That's a significant feature to add.

**Comment by asottile** [comment]
Sounds good to me, looking forward to reviewing :)

**Pull request merged**
