### PR TITLE
Feature: add precision parameter

### PR DESCRIPTION
**Pull request by astagi**

### CODE REVIEW

**Comment by dahlia** [comment]
Thanks for your effort!  Could you write some docs about the parameter?  It wouldn’t only be helpful for libsass-python users, but help me to understand what is the parameter for as well!

**Comment by astagi** [comment]
No problem :) Latest commit adds some doc. "precision" parameter set the precision for numbers, for example if you specify precision=8 you'll get numbers with a precision of 8 decimal places:

    $font-stack:    Helvetica, sans-serif;
    $primary-color: #333;
    $variabile: 5 / 3 * 6 / 7;
    body {
        font: 100% $font-stack;
        color: $primary-color;
        height: $variabile;
    }

the compiled css will result:

    body {
        font: 100% Helvetica, sans-serif;
        color: #333;
        height: 1.42857143; }

With precision = 5, "height" would be equal to 1.42857

**Comment by dahlia** [comment]
Merged!

**Comment by astagi** [comment]
:+1:

**Pull request merged**
