### PR TITLE
3.2.5 Closes #79

### LINKED ISSUE #79: Upgrade to libsass 3.2.5
3.2.4 has a regression, failing compilation on certain selectors:

https://github.com/sass/libsass/issues/1214

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by dahlia** [comment]
Sorry for really late response.  Let’s merge this!

**Comment by asottile** [comment]
@dahlia if you want I could become a "maintainer" and just merge these in the future if it's easier for you

**Comment by dahlia** [comment]
@asottile That seems a good idea.  I’m going to add you as a maintainer now.

**Comment by dahlia** [comment]
@asottile I just added you as a maintainer.  :smile:

**Comment by asottile** [comment]
<3<3

**Pull request merged**
